## Loading an Example Dataset 

In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)
digits.target


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


array([0, 1, 2, ..., 8, 9, 8])

## Learning and Predicting using SVM 

In [3]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)
clf.fit(digits.data[:-1], digits.target[:-1])
clf.predict(digits.data[-1:])

array([8])

## TypeCasting Conventions 

In [4]:
import numpy as np
from sklearn import kernel_approximation

rng = np.random.RandomState(0)
x = rng.rand(10,2000)
x = np.array(x, dtype='float32')
x.dtype

dtype('float32')

## Refitting and Updating Parameters 

In [6]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC

X,y = load_iris(return_X_y=True)
clf = SVC()
clf.set_params(kernel='linear').fit(X,y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [7]:
clf.set_params(kernel='rbf').fit(X,y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

## Multiclass vs Multilabel Fitting 

In [8]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

X=[[1,2],[2,4],[4,5],[3,2],[3,1]]
y=[0,0,1,1,2]

classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

array([0, 0, 1, 1, 2])

In [10]:
from sklearn.preprocessing import MultiLabelBinarizer
y=[[0,1], [0,2], [1,3], [0,2,3], [2,4]]

y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X,y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])